#!/usr/bin/env bash

go test -race -count=1 ./... 
go test -count=1 ./... -long 
go test -count=10 -p=5 ./...
go test ./tests -run=^$ -bench=BenchmarkRealisticWorkload -benchtime=30s -count=1 -v
go test -bench=. ./...
go test ./tests -run=^$ -bench=BenchmarkStorage -benchtime=30s -count=1 2>&1 | grep -E "^Benchmark|writes/sec|reads/sec|deletes/sec|checks/sec|info/sec|ops/sec|nav/sec"
