#!/usr/bin/env bash

time go test -race -count=1 ./... 
time go test -count=1 ./... -long 
time go test -count=10 -p=5 ./...
time go test ./tests -run=^$ -bench=BenchmarkRealisticWorkload -benchtime=30s -count=1 -v
time go test -bench=. ./...
time go test ./tests -run=^$ -bench=BenchmarkStorage -benchtime=30s -count=1 2>&1 | grep -E "^Benchmark|writes/sec|reads/sec|deletes/sec|checks/sec|info/sec|ops/sec|nav/sec"
