#!/usr/bin/env bash

go test -race -count=1 ./... 
go test -count=1 ./... -long 
go test -count=10 -p=5 ./...
go test ./tests -run=^$ -bench=BenchmarkRealisticWorkload -benchtime=30s -count=1 -v
go test -bench=. ./...
