// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/ouroboros.proto

package ouroboros_kv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KvDataHashProto represents the metadata for stored data with chunk hashes
type KvDataHashProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`                                    // Key of the content (hash.Hash as bytes)
	ChunkHashes   [][]byte               `protobuf:"bytes,2,rep,name=chunk_hashes,json=chunkHashes,proto3" json:"chunk_hashes,omitempty"` // Hashes of chunk payloads
	Parent        []byte                 `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`                              // Key of the parent chunk
	Created       int64                  `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`                           // Unix timestamp when the data was created
	Aliases       [][]byte               `protobuf:"bytes,5,rep,name=aliases,proto3" json:"aliases,omitempty"`                            // Aliases for the data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KvDataHashProto) Reset() {
	*x = KvDataHashProto{}
	mi := &file_proto_ouroboros_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KvDataHashProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KvDataHashProto) ProtoMessage() {}

func (x *KvDataHashProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ouroboros_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KvDataHashProto.ProtoReflect.Descriptor instead.
func (*KvDataHashProto) Descriptor() ([]byte, []int) {
	return file_proto_ouroboros_proto_rawDescGZIP(), []int{0}
}

func (x *KvDataHashProto) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KvDataHashProto) GetChunkHashes() [][]byte {
	if x != nil {
		return x.ChunkHashes
	}
	return nil
}

func (x *KvDataHashProto) GetParent() []byte {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *KvDataHashProto) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *KvDataHashProto) GetAliases() [][]byte {
	if x != nil {
		return x.Aliases
	}
	return nil
}

// SliceRecordProto represents a single Reed-Solomon slice persisted in the key-value store
type SliceRecordProto struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChunkHash       []byte                 `protobuf:"bytes,1,opt,name=chunk_hash,json=chunkHash,proto3" json:"chunk_hash,omitempty"`                   // Hash of the clear chunk
	SealedHash      []byte                 `protobuf:"bytes,2,opt,name=sealed_hash,json=sealedHash,proto3" json:"sealed_hash,omitempty"`                // Hash of the sealed chunk prior to RS encoding
	RsDataSlices    uint32                 `protobuf:"varint,3,opt,name=rs_data_slices,json=rsDataSlices,proto3" json:"rs_data_slices,omitempty"`       // Number of data slices in the originating stripe
	RsParitySlices  uint32                 `protobuf:"varint,4,opt,name=rs_parity_slices,json=rsParitySlices,proto3" json:"rs_parity_slices,omitempty"` // Number of parity slices in the originating stripe
	RsSliceIndex    uint32                 `protobuf:"varint,5,opt,name=rs_slice_index,json=rsSliceIndex,proto3" json:"rs_slice_index,omitempty"`       // Index of the slice within the stripe
	Size            uint64                 `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`                                             // Size of the slice payload
	OriginalSize    uint64                 `protobuf:"varint,7,opt,name=original_size,json=originalSize,proto3" json:"original_size,omitempty"`         // Size of the sealed chunk before RS split
	EncapsulatedKey []byte                 `protobuf:"bytes,8,opt,name=encapsulated_key,json=encapsulatedKey,proto3" json:"encapsulated_key,omitempty"` // ML-KEM encapsulated secret for the sealed chunk
	Nonce           []byte                 `protobuf:"bytes,9,opt,name=nonce,proto3" json:"nonce,omitempty"`                                            // AES-GCM nonce for encryption
	Payload         []byte                 `protobuf:"bytes,10,opt,name=payload,proto3" json:"payload,omitempty"`                                       // Slice payload after RS encoding
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SliceRecordProto) Reset() {
	*x = SliceRecordProto{}
	mi := &file_proto_ouroboros_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SliceRecordProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SliceRecordProto) ProtoMessage() {}

func (x *SliceRecordProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ouroboros_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SliceRecordProto.ProtoReflect.Descriptor instead.
func (*SliceRecordProto) Descriptor() ([]byte, []int) {
	return file_proto_ouroboros_proto_rawDescGZIP(), []int{1}
}

func (x *SliceRecordProto) GetChunkHash() []byte {
	if x != nil {
		return x.ChunkHash
	}
	return nil
}

func (x *SliceRecordProto) GetSealedHash() []byte {
	if x != nil {
		return x.SealedHash
	}
	return nil
}

func (x *SliceRecordProto) GetRsDataSlices() uint32 {
	if x != nil {
		return x.RsDataSlices
	}
	return 0
}

func (x *SliceRecordProto) GetRsParitySlices() uint32 {
	if x != nil {
		return x.RsParitySlices
	}
	return 0
}

func (x *SliceRecordProto) GetRsSliceIndex() uint32 {
	if x != nil {
		return x.RsSliceIndex
	}
	return 0
}

func (x *SliceRecordProto) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SliceRecordProto) GetOriginalSize() uint64 {
	if x != nil {
		return x.OriginalSize
	}
	return 0
}

func (x *SliceRecordProto) GetEncapsulatedKey() []byte {
	if x != nil {
		return x.EncapsulatedKey
	}
	return nil
}

func (x *SliceRecordProto) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *SliceRecordProto) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_proto_ouroboros_proto protoreflect.FileDescriptor

const file_proto_ouroboros_proto_rawDesc = "" +
	"\n" +
	"\x15proto/ouroboros.proto\x12\vouroboroskv\"\x92\x01\n" +
	"\x0fKvDataHashProto\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12!\n" +
	"\fchunk_hashes\x18\x02 \x03(\fR\vchunkHashes\x12\x16\n" +
	"\x06parent\x18\x03 \x01(\fR\x06parent\x12\x18\n" +
	"\acreated\x18\x04 \x01(\x03R\acreated\x12\x18\n" +
	"\aaliases\x18\x05 \x03(\fR\aaliases\"\xdc\x02\n" +
	"\x10SliceRecordProto\x12\x1d\n" +
	"\n" +
	"chunk_hash\x18\x01 \x01(\fR\tchunkHash\x12\x1f\n" +
	"\vsealed_hash\x18\x02 \x01(\fR\n" +
	"sealedHash\x12$\n" +
	"\x0ers_data_slices\x18\x03 \x01(\rR\frsDataSlices\x12(\n" +
	"\x10rs_parity_slices\x18\x04 \x01(\rR\x0ersParitySlices\x12$\n" +
	"\x0ers_slice_index\x18\x05 \x01(\rR\frsSliceIndex\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x04R\x04size\x12#\n" +
	"\roriginal_size\x18\a \x01(\x04R\foriginalSize\x12)\n" +
	"\x10encapsulated_key\x18\b \x01(\fR\x0fencapsulatedKey\x12\x14\n" +
	"\x05nonce\x18\t \x01(\fR\x05nonce\x12\x18\n" +
	"\apayload\x18\n" +
	" \x01(\fR\apayloadB\x1fZ\x1dgithub.com/i5heu/ouroboros-kvb\x06proto3"

var (
	file_proto_ouroboros_proto_rawDescOnce sync.Once
	file_proto_ouroboros_proto_rawDescData []byte
)

func file_proto_ouroboros_proto_rawDescGZIP() []byte {
	file_proto_ouroboros_proto_rawDescOnce.Do(func() {
		file_proto_ouroboros_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ouroboros_proto_rawDesc), len(file_proto_ouroboros_proto_rawDesc)))
	})
	return file_proto_ouroboros_proto_rawDescData
}

var file_proto_ouroboros_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ouroboros_proto_goTypes = []any{
	(*KvDataHashProto)(nil),  // 0: ouroboroskv.KvDataHashProto
	(*SliceRecordProto)(nil), // 1: ouroboroskv.SliceRecordProto
}
var file_proto_ouroboros_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ouroboros_proto_init() }
func file_proto_ouroboros_proto_init() {
	if File_proto_ouroboros_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ouroboros_proto_rawDesc), len(file_proto_ouroboros_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_ouroboros_proto_goTypes,
		DependencyIndexes: file_proto_ouroboros_proto_depIdxs,
		MessageInfos:      file_proto_ouroboros_proto_msgTypes,
	}.Build()
	File_proto_ouroboros_proto = out.File
	file_proto_ouroboros_proto_goTypes = nil
	file_proto_ouroboros_proto_depIdxs = nil
}
